include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_put_required_named_parameters_first: true
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    prefer_double_quotes: false
    public_member_api_docs: true
    always_specify_types: true
    lines_longer_than_80_chars: false

analyzer:
  exclude: [lib/generated_plugin_registrant.dart, build/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
  errors:
    always_specify_types: ignore
    public_member_api_docs: ignore
    todo: ignore
